id: P000176
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །རྒྱལ་སྲས་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  layers:
  - book_title
  - author
  - tsawa
  - quotation
  id: SHE-SHAP-04
web_metadata:
  title:
    en: The Book of Emanated Scriptures of the Bodhisattva
    bo: རྒྱལ་སྲས་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 4
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༤
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-04
  category:
    en: Mind Training
    bo: བློ་སྦྱོང།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-04.epub
  description:
    en: ''
    bo: ''
